//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Eventos = new HashSet<Eventos>();
            this.Empresas1 = new HashSet<Empresas>();
        }
    
        public int Id_cliente { get; set; }
        public int Id_empresa { get; set; }
        public int Id_estado { get; set; }
        public string Nome { get; set; }
        public System.DateTime DN { get; set; }
        public string Morada { get; set; }
        public string Localidade { get; set; }
        public string Cod_postal { get; set; }
        public string NIF { get; set; }
        public int Codigo { get; set; }
        public string Email { get; set; }
        public string Telemovel { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventos> Eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresas> Empresas1 { get; set; }
    }
}
